version: "3.8"

services:
  postgres:
    image: postgres:16-alpine
    container_name: stm-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: stmuser
      POSTGRES_PASSWORD: stmpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-sql:/docker-entrypoint-initdb.d #Create multiple DBs automatically

volumes:
  postgres_data:
  
