version: "3.8"

services:
  
  kafka:
    image: confluentinc/confluent-local:latest
    container_name: smt-kafka
    hostname: kafka
    ports:
      - "9091:9092"
      - "8082:8082"
    environment:
      KAFKA_KRAFT_CLUSTER_ID: "4V4Z-1L-0M-1N-0E"

  postgres:
    image: postgres:16-alpine
    container_name: stm-postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: stmuser
      POSTGRES_PASSWORD: stmpassword
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-sql:/docker-entrypoint-initdb.d #Create multiple DBs automatically

volumes:
  postgres_data:
  
